#!/bin/bash
rm -rf "./data_src"
rm -rf "./data_dst"
rm -rf "./model"
mkdir "./data_src"
mkdir "./data_src/aligned"
mkdir "./data_src/aligned_debug"
mkdir "./data_src/aligned_notrain"
mkdir "./data_dst"
mkdir "./data_dst/aligned"
mkdir "./data_dst/aligned_debug"
mkdir "./data_dst/aligned_notrain"
mkdir "model"
